// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tgv-website/BoldDynamic.tsx": () => import("../components/mockups/tgv-website/BoldDynamic.tsx"),
  "./components/mockups/tgv-website/DarkPrestige.tsx": () => import("../components/mockups/tgv-website/DarkPrestige.tsx"),
  "./components/mockups/tgv-website/LightSophistication.tsx": () => import("../components/mockups/tgv-website/LightSophistication.tsx"),
  "./components/mockups/tgv-website/MinimalistExecutive.tsx": () => import("../components/mockups/tgv-website/MinimalistExecutive.tsx")
};
